using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

public class Enums
{
    public enum Action
    {
        NONE = -1,
        ALL = 0,
        VIEW = 1,
        CREATE = 2,
        UPDATE = 3,
        DELETE = 4,
        PRINT = 5,
        EXPORT = 6,
        APPROVE = 7,
        SELECT = 8,
        DEPENDANCY = 9,
        SELECTBYSLABTYPE = 10,
        DELETEALL = 11,
        CHECKLOGIN = 12,
        LIST = 13,
        SELECTBYBANKID,
        REJECT = 16,
        TEST = 17,
        CLOSE,
        PRINTNCLOSE,
        PRINTLOG,
        PRINTPACKAGE,
        CLOSEPACKAGE,
        PRINTNCLOSEPACKAGE,
        DISCOUNT,
        PRINTUTILIZEPACKAGE,
        CLOSEUTILIZEPACKAGE,
        PRINTNCLOSEUTILIZEPACKAGE,
        CHECKVALIDMEMBERLOGIN,
        UPDATETare,
        UPDATEGross,
        UPDATEGrossRec,
        UPDATETareRec,
        RemoveGrossTareWeight,
        UPDATETLINEITEM,
        UPDATEINVOICEDETAIL,
        DELETELINE,
        DELETEALLLINE,
        UPDATEINVOICEPAYMENTDETAIL,
        CHANGEPASSWORD,
        UPDATEONLINEORDER
    }

    public enum Forms
    {
        Tenants = 1,
        Users = 2,
        Settings = 3
    }

    public enum Roles
    {
        Admin = 1,
        Back_Office = 2,
        Field_Staff = 3
    }


    public enum Languages
    {
        English = 1,
        हिंदी = 2,
        ગુજરાતી = 3,
        French = 4,
        Thai = 5
        //తెలుగు = 4
    }

    public enum Transactions
    {
        Login,
        Users = 1,
        UserAccGrpRestriction,
        State = 2,
        Country = 3,
        PriceList = 4,
        SalesExe = 5,
        SalesArea = 6,
        ItemGrp = 7,
        TaxNoStp = 8,
        Currency = 9,
        CurrencyConversion,
        Unit = 10,
        VoucherTyp = 11,
        Account = 12,
        AccountGrp = 13,
        Company = 14,
        AccountVoucher = 15,
        Tax = 16,
        OrderType = 17,
        Item = 18,
        GRType = 19,
        GR = 20,
        Store = 21,
        PIType = 22,
        SIType = 23,
        PI = 24,
        SDType = 25,
        SI = 26,
        SD = 27,
        InvestmentType,
        BanquetMenuCategory,
        ApprovalUserGroup,
        BanquetMenuItem,
        Venue,
        PaymentTerm,
        OpeningStock,
        LogInventoryType,
        SR,
        AssetDepriciationConfig,
        PR,
        CreditNote,
        DebitNote,
        Department,
        StockMovementType,
        StockTransferType,
        StockTransfer,
        TermsAndCondition,
        WeighBridgeEntry,
        TransportationRequestForm,
        TareWeight,
        GrossWeight,
        PO,
        SO,
        SOAdditionalDetails,
        PF,
        UpdateValuation,
        TaxFormsTypes,
        Coupons,
        Partner,
        ActivationCode,
        BranchAccountingConfiguration,
        BranchVoucherConfiguration,
        Contact,
        Schedule,
        CRMLeadStage,
        CRMLeadStageLostReason,
        CRMLeadSource,
        CRMIndustryType,
        CRMFollowUp,
        CRMLeads,
        CRMSurveyDefinition,
        CRMSurveyQuestion,
        CRMSurveyUserAnswer,
        Services,
        ServiceGrp,
        QuotationType,
        SQ,
        CustomerProfile,
        CRMCampaign,
        CRMLeadStatus ,
        Plant,
        SalesChannels,
        SalesDivisions,
        SalesRegions,
        SalesTerritories,
        SalesPriceListComponent,
        SalesPriceListTemplate,
        SalesDealCalculation,
        SalesGeneralStructure,
        SalesQuotationType,
        SalesQuotation,
        BuyerGroup,
        BudgetGroup,
        Budget,
        Roles,
        Machine,
        MachineGroup,
        BusinessAreas,
        PredefinedNarrations,
        CostGroups,
        CostCentres,
        PrjMappingConfig,
        NumberRange,
        SchemeGroup,
        CustomNumberRange,
        RefAdjustment,
        AttributesDefinition,
        AttributeChoice,
        ItemAttributes,
        ItemAttributesGroup,
        GblItemTaxDeails,
        GblServiceTaxDetails,
        Brand,
        FinanceType,
        Financer,
        Catalog,
        ProcessMaster,
        Overhead,
        ST,
        BOM,
        UserRole,
        TDSDeducteeType,
        TDSLowerDeduction,
        TDSNatureofPayment,
        AssetsInsuranceType,
        AssetsGrp,
        Assets,
        AssetsCategory,
        AssetsLocation,
        PRDORD,
        PTRC,
        PRDPOType,
        GIPRDORD, // Goods Issue Against Production Order
        GRPRDORD, // Goods Receive Against Production Order,
        GRPRDOSI,// Goods Receive Against Production Order Serial Item Mapping,
        RMItemSerialNoReplace,// Serial Item Mapping Replace Serial No,
        ProjectType,
        ProjectSkill,
        ProjectPortfolio,
        ProjectOtherCharges,
        ProjectMaster,
        PRJActivity,
        Workspace,
        InventoryPeriodClosing,
        AccountPeriodClosing,
        City,
        Taluka,
        Village,
        Hobby,
        LeaveType,
        LeaveGroup,
        LeaveGroupAssignToGrade,
        Qualification,
        EmployeeType,
        Skills,
        Position,
        Grade,
        Division,
        Designation,
        SeparationTypes,
        SeparationReason,
        PayrollComponent,
        RelationshipMaster,
        IndustryMaster,
        PTSlab,
        Shift,
        Employee,
        Task,
        HolidayCalendar,
        PFSettings,
        LWFSlabs,
        ESICSettings,
        StockJournal,
        TT,
        IndentType,
        StockTransferReqType,
        PRDIndent,
        ChqPrintingSettings,
        BOQ,
        BOQGroup,
        BOQActivityMaster,
        PRDProcessLossReasons,
        TDSRates,
        Activity,
        Cuisine,
        Interest,
        Sports,
        Product,
        MemberShipManagement,
        TermsandConditions,
        ChequeReceipt,
        HSNCode,
        GenericResource,
        ProjectSchedule,
        SalesTarget,
        CustomReport,
        AssetsDepreciationCalculation,
        ClubMemberWalletLedgerAccountConfig,
        ClubEventBookingInvoiceConfiguration,
        ClubEventSchemeConfiguration,
        ClubMemberFeedbackReviewSuggestion,
        ClubMemberEarnRewardPointConfiguration,
        CustItemSerialNoMapping,// Set  Cust ItemSerial No Mapping
        CustRMItemSerialNoReplace,
        YearlyPeriodicStockValueMaster,
        // Transactions for TMS Start
        CheckListTemplate,
        WorkspaceMaster,
        TaskMaster,
        MeetingManagement,
        // Transactions for TMS End
        PRDProcessConfi,
        HRLanguage,
        PayrollGroup,
        HRBankMaster,
        ProductGroup,
        ProductCategory,
        EventType,
        EventTopic,
        MemberActivity,
        PayrollGenerate,
        PRJStandardUnitConversion,
        Events,
        ActivityMember,
        ActivityPackages,
        StockClBal,
        GI,
        INVGR,
        RTPRDORD,
        // Quality Control
        QCTestParameterMaster,
        QCTestMethodMaster,
        QCTestListMaster,
        QCTestTempMaster,
        QCOrderType,
        QCOrder,
        SubTerritory,
        Retail,
        BankBranchMaster,
        ProjectSite,
        AttendanceMachineMaster,
        ExciseChapterHead,
        PurchaseRequisitionType,
        PurchaseInquiryType,
        WBEntryPassTypes,
        CSPAllowedItemGroups,
        PurRequisition,
        LangResources,
        Route,
        ChangePass,
        TransportMode,
        InsurancePolicy,
        RetailCategories,
        PrjUnitLocation,
        ProjectSetup,
        SalesReturnReason,
        ProjectSetupStatus,
        ImpexTermsAndConditions,
        GateInward,
        GateOutward,
        AdditionalCharge,
        AdditionalChargeTemplate,
        CSPLogInvNumberRange,
        SalesBooking,
        Enterprises,
        HelpPages,
        HelpMenus,
        POSMenuGroups,
        POSRetailOutletMaster,
        POSRetailCustomerList,
        POSMenuDefinitionGroups,
        POSMenuDefinition,
        POSMenuDefinitionItems,
        Calendar,
        POSMenuDefinitionModifier,
        PublishDocument,
        LeaveRequest,
        AttendanceRegularization,
        AttendanceRegularizationReasons,
        StorelinkSalesTerritory,
        SalesExecutiveCommission,
        DBmaintenance,
        //CSP
        CSPDevices,
        CSPAppAlerts,
        CSPFeedbackMaster,
        CSPInquiryMaster,
        CSPUsers,
        // HRMS - Travel Managment
        TravelTypes,
        TravelModes,
        TravelClasses,
        HRTravelRequest,
        ApprovalScheme,

        //ESS
        ESSTravelRequest,
        ESSClaimRequest,
        ESSHREmpReturnAsset,
        ESSUpdateMyProfile,

        // HRMS - Advance & Claim
        AdvanceType,
        HRClaimType,
        AdvanceLimit,
        EventRegistration,
        PaymentPlan,
        POSNumberRange,
        HRClaimRequest,
        ITaxSlabs,
        RentReceipt,
        HRAssetTypes,
        HRAsset,
        HREmpAssetAssign,
        HREmpReturnAsset,
        TDSConfiguration,
        HRDocumentType,
        POSPackageMaster,
        PaymentMode,
        Scheme,
        Reason,
        BlockPayroll,
        CollectionPlan,
        StkPeriodClosing,
        SchemeGroupBulkUpdate,
        SchemeWiseAllowedAccount,
        HRClaimPolicy,
        HRAssignClaimPolicy,
        TTR, //Stock Transfer Reqeust Code
        EmployeeSeparation,
        BanquetPackage,
        BanquetEnquiry,
        Measurement,
        PrjProjectZone,
        DayArrear,
        IncrementArrear,
        EmployeeTDSDeclaration,
        PurchaseInquiry,
        Checklist,
        ESSTDSDeclaration,
        ClubMediaMaster,//Club
        ClubCheckInMaster,//Club
        ClubAppAlerts,//Club
        ClubAccountVoucher,
        HRKPI,
        POSInvoiceMaster, //POS
        HROverTimeSettings,
        PrjProjectMileston_SP,
        PhysicalInventory,
        BanquetOrder,
        CreditLimitType,
        AmenitiesMaster,
        CentralizedAccVoucher,
        BudgetEntry,
        DisbursePayroll //HRMS
       ,
        POSSalesSchemeMaster //POS
            , HREmpAssignPerHourRate, //HRMS
        OverTimeAttendance, //HRMS
        POSVehicleRegistration, //POS
        POSEditBillEmailConfiguration, //POS
        POSApproveWasteLossTrans,
        ClaimType,//ERP Claim Process
        ClaimReason, //ERP Claim Process
        ClaimRequest, //ERP Claim Request        
        MagazinesMaster,
        ConstructionMaster,
        PackagesMaster,
        ClubPhotoMaster,
        PAYESlabs,
        POSPendingInvoicePostFromDevice,
        SFAMobileAppConfigure, //ZIPSFA Mobile App configure
        DiscountType,
        PendingReasonGroup,
        ModeofAcknowledgement,
        TechnicianMaster,
        ItemMultiDiscountTrans,
        POSPrinterCategories,
        HRVehicleType, //HRMS             
        ClubCancelEventTicket,
        POSProductCatalogue,
        POSProductCatalogueGroups,
        POSProductCatalogueItems,
        CRMConfiguration,
        POSLoyaltyProgramMaster,
        OtherAdditionDeductionTemplate,
        HRCheckInTypeMaster,
        CreditLimitPeriodRequest,
        POSCurrencyConversion,
        POSExchangeSchemeMaster,
        AdvReceiptAgstOrder,


        //Market Information
        MarketInformation,

        // Job Work
        JO,
        JobworkLogInventoryType,
        JWI,
        JWR,
        JobworkGI,
        JobworkGIWO,
        JobworkGR,
        JobworkGRWO,
        JWGR, // Job Work Goods Return

        RebateScheme,
        EmployeeTaxDepositeDetails,
        rptRebateSchemeSettlement,
        PRDPlan,
        HREarlyLeave,
        ESSEarlyLeave,
        POSMenuDefinitionUser,
        LogisticDeviceMaster,
        AutoSerialNoConfig,
        LoginDeviceRegistration, //LoginSecurity
        POSLogisticRouteMaster,
        PaymentRequestType,
        PaymentRequest,
        MultiplePaymentRequest,
        HRCompOffCredit,
        LogisticRouteMaster,
        LogisticDispatchPlanning,
        AccountCostcentreMapping,
        AssignAssetLocationToUser,
        AssetMovement,
        AssetConditions,
        InventoryToAssetConversion,
        AssetComplaints,
        AssetMaintenance,
        CSPRetailer,
        LogisticReasonMaster,
        LogisticDispatchItemConfig,
        LogisticDispatchStoreItemMapping,
        CSPSecondarySalesOrder,
        AssetAudit,
        AssetGoodsIssueType,
        AssetGoodsIssue,
        HRAdvanceSummary,
        HRF_FRegister,
        AssetGoodReceiveType,
        AssetPreventiveChecklist,
        AssetDisposalType,
        AssetGoodsReceive,
        AssetPreventiveMaintenance,
        AssetDisposal,
        EmailSMSSchedule,
        HRPTRCNoSetup, //Hr RC No Setup
        VATOnImport,
        HRLeaveAutoCreditSlab,
        AssetComplaintMaster,
        HRLeaveAutoCredit,
        VoucherNarration,
        CRMProject,
        HRDAMasterEntry,
        TDSPaymentEntry,
        HRF_FCalculation,
        HRPayrollSettings,
        HRrptFoodGrainLoan,
        HRrptLoanOutstanding,
        HRrptLoandeduction,
        HRrptMonthlyLoandeduction,
        HRrptBankStatementForLoan,
        HRGratuitySettings,
        HRGratuityCalculation,
        IncrementProjectionRequest,
        IncrementProjectionSlab,
        POSReferenceCodeSchemeMaster,
        AssetClassMaster,
        EmployeePITExemption, //HRMS
        PITaxSlabs, //HRMS
        ESSPITExemption,
        StorewiseItemConfiguration,
        MachineType,
        StockReservation,
        POSCustomerWalkIn,
        AssignRolesToMultipleUser,
        HRSkipLoanInstallments,
        HROptionalHolidayCalendar,
        ESSOptionalHolidayRequest,
        HROptionalHolidayRequest,
        AccScheduleMaster,
        HRAdvanceRequest,
        HRPFManagementPFSettings,
        HRPFLoanSettings,
        HRPFOpeningBalance,
        HRPFLoanRequest,
        POSConsolidateInvoice,
        HRSkipPFLoanInstallments,
        HRrptPFLoanOutstanding,
        HRrptPFLoandeduction,
        HRrptBankStatementForPFLoan,
        HRrptPFLoanRegister,
        HRLeaveCancellationRequest,
        ESSLeaveCancellationRequest,
        HRBonusSettings,
        HRrptBankStatementForBonus,
        HRrptBonusRegister,
        ESSResignationRequest,
        POSRetailCustomerType,
        ItemMOP,
        ClubShiftMaster,
        PQ,
        POSOutletUserRoles,
        HREmployeeMovement,
        HRDistrictMaster,
        HRTehsilMaster,
        HRVillageMaster,
        HRFieldVisitType,
        ESSFieldVisit,
        HRFieldVisit,
        ESSAnnualFieldVisitPlan,
        HRAnnualFieldVisitPlan,
        ESSMonthlyFieldVisitPlan,
        HRMonthlyFieldVisitPlan,
        HRVoucherPosting,
        HRChangeEmpCode,
        POSOutletOperation,
        POSRetailOutletWiseOperation,
        StockCategoryMaster,
        HRrptESICRegister,
        BOQForm,
        TCSCollecteeType,
        TCSNatureofGoods,
        ComplainMaster,
        AdBOM,
        AdPRDPO,
        PRDIssueSlipReqType,
        PRDIssueSlipReq,
        PRDIssueSlip,
        PRDMovementSlipReq,
        PRDMovementSlip,
        NotificationAndScientificPaper,
        PRDPlanningRequestType,
        PRDPlanningRequest,
        CustomerLoyaltyPointsAdjustment,
        CustomerLoyaltyPointsRedeemRequest,
        RudiWiseTargetEntry, //Rudi 
        PlantWiseTargetEntry, //Plant
        POSCustomerWiseDiscountScheme,
        LetterTemplate,
        PeriodicProcessingReportLOG,
        POSCustomerWiseMultipleInvoiceScheme,
        BinMaster,
        ItemBinMappingTrans,
        HRDateWisePunchEntry, //HRMS
        ESSReporteesLeave, // ESS
        DynamicReport,
        HRCertificate,
        ClubMemberRewardProgramConfiguration,
        ClubMemberRewardPointsAdjustment,
        PasswordPolicy, 
        PRDItemSerialNumberMappingType,
        POSReeloLoyaltyProgramConfiguration,        
        TDSSectionActivation, //HRMS
        HRNotificationSettings,
        WhatsAppFacebookSettings,
        PSBGType,
        BGForm,
        TrustTagsIntegration,
        GEMStage,
        GEMProduct,
        TenderForm,
        TenderEnquiryMode,
        EmployeeConfirmationRequest,
        IncidentStatus,
        IncidentForm,
        Vertical
    }

    public enum ResponseMessage
    {
        SESSIONOUT = -1,
        SUCCESS = 0,
        ERROR = 1,
        INVALID = 2,
        WARNING = 3,
        VALIDATION_ERROR = 4,
        INFORMATIONAL = 5,
    }

    public enum TASKACTION_OBJECTTYPE
    {
        LEAD = 1
    }

    public enum AGGridFilterType
    {
        agNumberColumnFilter=1,
        agTextColumnFilter=2,
        agDateColumnFilter=3,
        agSetColumnFilter=4
    }

    public enum AGGridColumnPinning
    {
        left=1,
        right=2
    }

    public enum AGGridAggregation
    {
        sum=1,
        min=2,
        max=3,
        first=4,
        last=5
    }
}